### ISSUE TITLE
Invalid imported build definition on GitLab 13.7.9

### ISSUE THREAD

**Issue by applejag** [iver-wharf/wharf-provider-gitlab#12]
We're used to GitLab v12.9.3, but just recently we've tested this provider with GitLab v13.7.9. It's not the most recent, but enough to break our importer.

![Screenshot_2021-06-10_11-46-03](https://user-images.githubusercontent.com/2477952/121503551-76081d80-c9e1-11eb-940d-f4eb28b95de5.png)

While the actual `.wharf-ci.yml` file looks like this:

```yml
run:
  run:
    container:
      image: ubuntu:latest
      cmds:
        - |
          echo "Hello world from ${REPO_GROUP}/${REPO_NAME} on branch ${REPO_BRANCH}"
```

Looking at the code,

https://github.com/iver-wharf/wharf-provider-gitlab/blob/d9b6f1646c8bedf7b5ad6bd05a22629396188967/gitlab.go#L97

it seems like we're using the following endpoint:

- Go reference: https://pkg.go.dev/github.com/xanzy/go-gitlab#RepositoryFilesService.GetRawFile
- GitLab v12 docs: https://docs.gitlab.com/12.10/ee/api/repository_files.html#get-raw-file-from-repository
- GitLab v13 docs: https://docs.gitlab.com/13.12/ee/api/repository_files.html#get-raw-file-from-repository

A manual test however on the endpoint in question does respond as expected (in contrast to what the refreshed project showed, with the `git-blob:...` string):

```console
$ curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://gitlab.*redacted.com*/api/v4/projects/60/repository/files/.wharf-ci.yml/raw?ref=master"
run:
  run:
    container:
      image: ubuntu:latest
      cmds:
        - |
          echo "Hello world from ${REPO_GROUP}/${REPO_NAME} on branch ${REPO_BRANCH}"
```

Unclear what's actually going on here. Needs further investigation.
